workspace:
  base: /home/emil/apps/go
  path: src/sample-app

pipeline:
  test:
    image: golang
    commands: 
    - go vet
    - go test -v -cover
      
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    secrets: [ docker_username, docker_password ]
    commands:
      - echo $DOCKER_USERNAME
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t vanneback/sample-app:latest .
      - docker tag vanneback/sample-app:latest 
        vanneback/sample-app:$(docker images | awk '($1 == "vanneback/sample-app" && $2 != "latest") {print $2 += .1; exit}')
      - docker push vanneback/sample-app:latest
      - docker push vanneback/sample-app:$(docker images | 
        awk '($1 == "vanneback/sample-app" && $2 != "latest") {print $2; exit}')

        
  deploy:
    image: lachlanevenson/k8s-kubectl:v1.10.10

    volumes:
      - /home/emil/.kube/v_kube_conf:/home/emil/.kube/config

    environment:
      - KUBECONFIG=/home/emil/.kube/config
    commands:
      - kubectl apply -f k8s/production.yaml
      - kubectl apply -f k8s/service.yaml
      
        #  docker:
#    image: plugins/docker
#    secrets: [ docker_username, docker_password ]
#    repo: vanneback/sample-app
#    tags: latest 
#    registry: vanneback/sample-app
#    insecure: true
