apiVersion: v1
kind: Service
metadata:
  labels:
    app: cd-jenkins
  name: cd-jenkins
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30500
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cd-jenkins
  sessionAffinity: None
  type: NodePort
