kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: go-sample-production
spec:
  replicas:
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
        env: production
    spec:
      containers:
      - name: sample-app
        image: vanneback/sample-app:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: go-sample
          containerPort: 80
