apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-sample
    env: production
    role: frontend
  name: go-sample-production
  namespace: default
spec:
  clusterIP: 10.98.66.90
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30489
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-sample
    env: production
    role: frontend
  sessionAffinity: None
  type: NodePort
