apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
    env: staging
  name: sample-app
  namespace: staging
spec:
  clusterIP: 10.98.66.90
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30490
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-app
    env: staging
  sessionAffinity: None
  type: NodePort
