apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
    env: production
  name: sample-app
  namespace: default
spec:
  clusterIP: 10.98.66.91
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30489
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-app
    env: production
  sessionAffinity: None
  type: NodePort
