apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
    env: staging
  name: sample-app
  namespace: staging
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-app
    env: staging
  sessionAffinity: None
  type: LoadBalancer
